create table if not exists public.profiles (
    id uuid primary key,
    email text not null,
    first_name text,
    last_name text,
    address text,
    mobile_number text,
    avatar_url text,
    is_premium boolean not null default false,
    premium_expiry timestamptz,
    free_download_count integer not null default 0,
    weekly_premium_download_count integer not null default 0,
    weekly_reset_date timestamptz not null default timezone('utc', now())
);

alter table public.profiles add column if not exists first_name text;
alter table public.profiles add column if not exists last_name text;
alter table public.profiles add column if not exists address text;
alter table public.profiles add column if not exists mobile_number text;
alter table public.profiles add column if not exists avatar_url text;

create table if not exists public.designs (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text,
    description text,
    price numeric not null default 0,
    is_free boolean not null default true,
    is_premium boolean not null default false,
    category text,
    image_url text,
    download_link text,
    downloads integer not null default 0,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.designs add column if not exists slug text;

create table if not exists public.purchases (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    design_id text not null,
    payment_id text not null unique,
    amount numeric not null,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles enable row level security;
alter table public.designs enable row level security;
alter table public.purchases enable row level security;

drop policy if exists "Users can read own user row" on public.profiles;
create policy "Users can read own user row"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert own user row" on public.profiles;
create policy "Users can insert own user row"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update own user row" on public.profiles;
create policy "Users can update own user row"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can read their own purchases" on public.purchases;
create policy "Users can read their own purchases"
on public.purchases
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Authenticated users can read designs" on public.designs;
create policy "Authenticated users can read designs"
on public.designs
for select
to authenticated
using (true);

drop policy if exists "Anon can read designs" on public.designs;
create policy "Anon can read designs"
on public.designs
for select
to anon
using (true);

create index if not exists purchases_user_design_idx
on public.purchases (user_id, design_id);

create index if not exists purchases_payment_id_idx
on public.purchases (payment_id);

create or replace function public.slugify_text(value text)
returns text
language sql
immutable
as $$
  select nullif(regexp_replace(regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', '-', 'g'), '(^-|-$)', '', 'g'), '');
$$;

create or replace function public.generate_unique_design_slug(source_value text, source_id bigint default null)
returns text
language plpgsql
as $$
declare
  base_slug text := coalesce(public.slugify_text(source_value), 'design');
  next_slug text := base_slug;
  slug_exists boolean;
  counter integer := 2;
begin
  loop
    if source_id is null then
      select exists (
        select 1
        from public.designs d
        where d.slug = next_slug
      ) into slug_exists;
    else
      select exists (
        select 1
        from public.designs d
        where d.slug = next_slug
          and d.id <> source_id
      ) into slug_exists;
    end if;

    exit when not slug_exists;

    next_slug := base_slug || '-' || counter;
    counter := counter + 1;
  end loop;

  return next_slug;
end;
$$;

create or replace function public.set_design_slug()
returns trigger
language plpgsql
as $$
begin
  new.slug := public.generate_unique_design_slug(coalesce(nullif(trim(new.slug), ''), new.title), new.id);
  return new;
end;
$$;

with normalized_design_slugs as (
  select
    id,
    coalesce(public.slugify_text(coalesce(nullif(trim(slug), ''), title)), 'design') as base_slug,
    row_number() over (
      partition by coalesce(public.slugify_text(coalesce(nullif(trim(slug), ''), title)), 'design')
      order by created_at, id
    ) as slug_rank
  from public.designs
)
update public.designs d
set slug = case
  when n.slug_rank = 1 then n.base_slug
  else n.base_slug || '-' || n.slug_rank
end
from normalized_design_slugs n
where d.id = n.id;

create unique index if not exists idx_designs_slug_unique on public.designs (slug);

drop trigger if exists set_design_slug on public.designs;
create trigger set_design_slug
before insert or update on public.designs
for each row execute function public.set_design_slug();



