create table if not exists public.profiles (
    id uuid primary key,
    email text not null,
    first_name text,
    last_name text,
    address text,
    mobile_number text,
    is_premium boolean not null default false,
    premium_expiry timestamptz,
    free_download_count integer not null default 0,
    weekly_premium_download_count integer not null default 0,
    weekly_reset_date timestamptz not null default timezone('utc', now())
);

alter table public.profiles add column if not exists first_name text;
alter table public.profiles add column if not exists last_name text;
alter table public.profiles add column if not exists address text;
alter table public.profiles add column if not exists mobile_number text;

create table if not exists public.designs (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    price numeric not null default 0,
    is_free boolean not null default true,
    is_premium boolean not null default false,
    category text,
    image text,
    preview_url text,
    download_link text,
    downloads integer not null default 0,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.purchases (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    design_id text not null,
    payment_id text not null unique,
    amount numeric not null,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles enable row level security;
alter table public.designs enable row level security;
alter table public.purchases enable row level security;

drop policy if exists "Users can read own user row" on public.profiles;
create policy "Users can read own user row"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert own user row" on public.profiles;
create policy "Users can insert own user row"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update own user row" on public.profiles;
create policy "Users can update own user row"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can read their own purchases" on public.purchases;
create policy "Users can read their own purchases"
on public.purchases
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Authenticated users can read designs" on public.designs;
create policy "Authenticated users can read designs"
on public.designs
for select
to authenticated
using (true);

drop policy if exists "Anon can read designs" on public.designs;
create policy "Anon can read designs"
on public.designs
for select
to anon
using (true);

create index if not exists purchases_user_design_idx
on public.purchases (user_id, design_id);

create index if not exists purchases_payment_id_idx
on public.purchases (payment_id);
