create table if not exists public.purchases (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    design_id text not null,
    payment_id text not null unique,
    amount numeric not null,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.purchases enable row level security;

drop policy if exists "Users can read their own purchases" on public.purchases;
create policy "Users can read their own purchases"
on public.purchases
for select
to authenticated
using (auth.uid() = user_id);

create index if not exists purchases_user_design_idx
on public.purchases (user_id, design_id);

create index if not exists purchases_payment_id_idx
on public.purchases (payment_id);
